# Generated by Django 5.2.12 on 2026-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
    ]
