# Generated by Django 5.2.12 on 2026-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_ocr_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gst_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
